"""autogenerated votes_alembic table

Revision ID: 4faf7cd7c61c
Revises: c6c5401577b9
Create Date: 2025-07-10 12:12:49.097372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4faf7cd7c61c'
down_revision: Union[str, Sequence[str], None] = 'c6c5401577b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes_alembic',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts_alembic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_alembic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes_alembic')
    # ### end Alembic commands ###